name: walkworld
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.9 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1
  flutter_svg: ^2.2.0
  #Flutter 的 iOS 风格图标库
  cupertino_icons: ^1.0.8  
  lpinyin: ^2.0.3
  sqflite: ^2.4.2+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true  #设为 true 后才能用 Flutter 内置的 Material 图标，否则图标不显示
  assets:
    - assets/icons/
    - assets/icons/tabbar/
    - assets/icons/motion/
    - assets/icons/profile/
    - assets/icons/home/
    - assets/icons/common/
    - assets/datas/
